/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login endpoint.
         *
         *     Para MVP: busca practitioner por email, password es "demo" para cualquier usuario.
         *     En producción: integrar con Supabase Auth.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current authenticated user.
         *
         *     Returns practitioner data for the authenticated user.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Patients
         * @description List patients with optional search.
         *
         *     - Search by partial name or DNI (minimum 2 characters)
         *     - Paginated results
         */
        get: operations["list_patients_api_v1_patients__get"];
        put?: never;
        /**
         * Create Patient
         * @description Create new patient.
         *
         *     Validates:
         *     - DNI format (Spanish DNI/NIE)
         *     - DNI uniqueness
         *     - Required fields
         */
        post: operations["create_patient_api_v1_patients__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Patient
         * @description Get patient by ID.
         *
         *     Returns full patient data including allergies and recent encounters.
         */
        get: operations["get_patient_api_v1_patients__patient_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Patient
         * @description Update patient data.
         */
        patch: operations["update_patient_api_v1_patients__patient_id__patch"];
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/allergies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Allergies
         * @description List patient allergies.
         */
        get: operations["list_allergies_api_v1_patients__patient_id__allergies_get"];
        put?: never;
        /**
         * Add Allergy
         * @description Add allergy to patient.
         */
        post: operations["add_allergy_api_v1_patients__patient_id__allergies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/allergies/{allergy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Allergy
         * @description Remove allergy from patient.
         */
        delete: operations["remove_allergy_api_v1_patients__patient_id__allergies__allergy_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/encounters/patient/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Patient Encounters
         * @description List all encounters for a patient.
         *
         *     Returns encounters with conditions and medications.
         */
        get: operations["list_patient_encounters_api_v1_encounters_patient__patient_id__get"];
        put?: never;
        /**
         * Create Encounter
         * @description Create new encounter for patient (FHIR Create interaction).
         *
         *     Creates Encounter + Condition(s) + MedicationRequest(s).
         */
        post: operations["create_encounter_api_v1_encounters_patient__patient_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/encounters/{encounter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Encounter
         * @description Get encounter by ID with full details.
         */
        get: operations["get_encounter_api_v1_encounters__encounter_id__get"];
        /**
         * Update Encounter
         * @description Update an existing encounter (FHIR R5 Update interaction).
         *
         *     Reemplaza campos SOAP y sub-recursos (Conditions, Medications)
         *     mediante estrategia delete + recreate.
         */
        put: operations["update_encounter_api_v1_encounters__encounter_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List treatment templates.
         */
        get: operations["list_templates_api_v1_templates__get"];
        put?: never;
        /**
         * Create Template
         * @description Create new treatment template.
         */
        post: operations["create_template_api_v1_templates__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Match Template
         * @description Find best matching template for a diagnosis.
         *
         *     Used for auto-loading treatment when selecting diagnosis.
         */
        get: operations["match_template_api_v1_templates_match_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get template by ID (incluye templates globales).
         */
        get: operations["get_template_api_v1_templates__template_id__get"];
        /**
         * Update Template
         * @description Update template. Solo templates propios (no globales).
         */
        put: operations["update_template_api_v1_templates__template_id__put"];
        post?: never;
        /**
         * Delete Template
         * @description Delete template. Solo templates propios (no globales).
         */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions/{encounter_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prescription Preview
         * @description Get prescription data for preview.
         *
         *     Returns structured data for frontend preview component.
         */
        get: operations["get_prescription_preview_api_v1_prescriptions__encounter_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions/{encounter_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Prescription Pdf
         * @description Generate prescription PDF.
         *
         *     Uses WeasyPrint to generate PDF from HTML template.
         */
        get: operations["download_prescription_pdf_api_v1_prescriptions__encounter_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check for deployment monitoring.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllergyCreate
         * @description Schema for creating an allergy.
         */
        AllergyCreate: {
            /** Code Text */
            code_text: string;
            /** Type */
            type?: string | null;
            /** Category */
            category?: string | null;
            /** Criticality */
            criticality?: string | null;
        };
        /**
         * AllergyResponse
         * @description Schema for allergy response.
         */
        AllergyResponse: {
            /** Code Text */
            code_text: string;
            /** Type */
            type?: string | null;
            /** Category */
            category?: string | null;
            /** Criticality */
            criticality?: string | null;
            /** Id */
            id: string;
            /** Clinical Status */
            clinical_status: string;
            /**
             * Recorded Date
             * Format: date-time
             */
            recorded_date: string;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /**
         * ConditionCreate
         * @description Schema para crear una Condition (diagnóstico).
         *
         *     Alineado con FHIR R5 Condition resource.
         */
        ConditionCreate: {
            /**
             * Code Text
             * @description Texto del diagnóstico
             */
            code_text: string;
            /**
             * Code Coding Code
             * @description Código CIE-10 u otro sistema de codificación
             */
            code_coding_code?: string | null;
        };
        /**
         * ConditionResponse
         * @description Condition response (FHIR R5 Condition resource).
         *
         *     Representa un diagnóstico clínico como recurso atómico independiente.
         */
        ConditionResponse: {
            /**
             * Id
             * @description Identificador único de la condición
             */
            id: string;
            /**
             * Code Text
             * @description Texto del diagnóstico
             */
            code_text: string;
            /**
             * Code Coding Code
             * @description Código de clasificación (CIE-10, etc)
             */
            code_coding_code?: string | null;
            /**
             * Clinical Status
             * @description Estado clínico: active | resolved | inactive
             */
            clinical_status: string;
        };
        /**
         * EncounterCreate
         * @description Schema para crear un Encounter (consulta médica).
         *
         *     Estructura transaccional: crea Encounter + Conditions + Medications en una sola operación.
         *     Alineado con FHIR R5 Encounter resource.
         */
        EncounterCreate: {
            /**
             * Reason Text
             * @description Motivo de consulta
             */
            reason_text?: string | null;
            /**
             * Subjective Text
             * @description Subjetivo (SOAP)
             */
            subjective_text?: string | null;
            /**
             * Objective Text
             * @description Objetivo (SOAP)
             */
            objective_text?: string | null;
            /**
             * Assessment Text
             * @description Análisis/Evaluación (SOAP)
             */
            assessment_text?: string | null;
            /**
             * Plan Text
             * @description Plan de tratamiento (SOAP)
             */
            plan_text?: string | null;
            /**
             * Recommendations Text
             * @description Recomendaciones
             */
            recommendations_text?: string | null;
            /**
             * Note
             * @description Nota libre (legacy)
             */
            note?: string | null;
            /**
             * Conditions
             * @description Diagnósticos vinculados a esta consulta
             */
            conditions?: components["schemas"]["ConditionCreate"][];
            /**
             * Medications
             * @description Prescripciones vinculadas a esta consulta
             */
            medications?: components["schemas"]["MedicationCreate"][];
        };
        /**
         * EncounterListResponse
         * @description Respuesta paginada de encounters.
         *
         *     Future-proof: preparado para migrar a FHIR Bundle con paginación por cursores.
         */
        EncounterListResponse: {
            /**
             * Items
             * @description Lista de encounters
             */
            items: components["schemas"]["EncounterResponse"][];
            /**
             * Total
             * @description Total de resultados disponibles
             */
            total: number;
        };
        /**
         * EncounterResponse
         * @description Encounter response (FHIR R5 Encounter resource).
         *
         *     Incluye recursos atómicos vinculados (Conditions, Medications).
         */
        EncounterResponse: {
            /**
             * Id
             * @description Identificador único del encounter
             */
            id: string;
            /**
             * Subject Id
             * @description Referencia al paciente (Patient.id)
             */
            subject_id: string;
            /**
             * Status
             * @description Estado: planned | in-progress | finished | cancelled
             */
            status: string;
            /**
             * Period Start
             * Format: date-time
             * @description Fecha/hora de inicio del encounter
             */
            period_start: string;
            /**
             * Reason Text
             * @description Motivo de consulta
             */
            reason_text?: string | null;
            /**
             * Subjective Text
             * @description Subjetivo (SOAP)
             */
            subjective_text?: string | null;
            /**
             * Objective Text
             * @description Objetivo (SOAP)
             */
            objective_text?: string | null;
            /**
             * Assessment Text
             * @description Análisis (SOAP)
             */
            assessment_text?: string | null;
            /**
             * Plan Text
             * @description Plan (SOAP)
             */
            plan_text?: string | null;
            /**
             * Recommendations Text
             * @description Recomendaciones
             */
            recommendations_text?: string | null;
            /**
             * Note
             * @description Nota consolidada (legacy)
             */
            note?: string | null;
            /**
             * Conditions
             * @description Diagnósticos de esta consulta
             */
            conditions?: components["schemas"]["ConditionResponse"][];
            /**
             * Medications
             * @description Prescripciones de esta consulta
             */
            medications?: components["schemas"]["MedicationResponse"][];
        };
        /**
         * EncounterUpdate
         * @description Schema para actualizar un Encounter (FHIR R5 Update interaction).
         *
         *     Semántica FHIR Update: reemplazo completo del contenido del recurso.
         *     Los campos omitidos (None) se limpian; conditions/medications se reemplazan.
         */
        EncounterUpdate: {
            /**
             * Reason Text
             * @description Motivo de consulta
             */
            reason_text?: string | null;
            /**
             * Subjective Text
             * @description Subjetivo (SOAP)
             */
            subjective_text?: string | null;
            /**
             * Objective Text
             * @description Objetivo (SOAP)
             */
            objective_text?: string | null;
            /**
             * Assessment Text
             * @description Análisis/Evaluación (SOAP)
             */
            assessment_text?: string | null;
            /**
             * Plan Text
             * @description Plan de tratamiento (SOAP)
             */
            plan_text?: string | null;
            /**
             * Recommendations Text
             * @description Recomendaciones
             */
            recommendations_text?: string | null;
            /**
             * Note
             * @description Nota libre (legacy)
             */
            note?: string | null;
            /**
             * Conditions
             * @description Diagnósticos (reemplazo completo)
             */
            conditions?: components["schemas"]["ConditionCreate"][];
            /**
             * Medications
             * @description Prescripciones (reemplazo completo)
             */
            medications?: components["schemas"]["MedicationCreate"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MedicationCreate
         * @description Schema para crear una MedicationRequest (prescripción).
         *
         *     Alineado con FHIR R5 MedicationRequest resource.
         */
        MedicationCreate: {
            /**
             * Medication Text
             * @description Nombre del medicamento
             */
            medication_text: string;
            /**
             * Dosage Text
             * @description Pauta de dosificación
             */
            dosage_text: string;
            /**
             * Duration Value
             * @description Valor de duración del tratamiento
             */
            duration_value?: number | null;
            /**
             * Duration Unit
             * @description Unidad de duración: días, semanas, meses
             */
            duration_unit?: string | null;
        };
        /** MedicationItem */
        MedicationItem: {
            /** Medication */
            medication: string;
            /** Dosage */
            dosage: string;
            /** Duration */
            duration: string;
        };
        /**
         * MedicationResponse
         * @description MedicationRequest response (FHIR R5 MedicationRequest resource).
         *
         *     Representa una prescripción médica como recurso atómico independiente.
         */
        MedicationResponse: {
            /**
             * Id
             * @description Identificador único de la prescripción
             */
            id: string;
            /**
             * Medication Text
             * @description Nombre del medicamento
             */
            medication_text: string;
            /**
             * Dosage Text
             * @description Pauta de dosificación
             */
            dosage_text: string;
            /**
             * Duration Value
             * @description Valor de duración
             */
            duration_value?: number | null;
            /**
             * Duration Unit
             * @description Unidad de duración
             */
            duration_unit?: string | null;
            /**
             * Status
             * @description Estado de la prescripción: active | completed | cancelled
             */
            status: string;
        };
        /**
         * PatientCreate
         * @description Schema for creating a patient.
         */
        PatientCreate: {
            /**
             * Identifier Value
             * @description DNI/NIE
             */
            identifier_value: string;
            /** Name Given */
            name_given: string;
            /** Name Family */
            name_family: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Gender */
            gender?: string | null;
            /** Telecom Phone */
            telecom_phone?: string | null;
            /** Telecom Email */
            telecom_email?: string | null;
        };
        /**
         * PatientListResponse
         * @description Paginated list of patients.
         */
        PatientListResponse: {
            /** Items */
            items: components["schemas"]["PatientSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PatientResponse
         * @description Full patient response with allergies and encounters.
         */
        PatientResponse: {
            /**
             * Identifier Value
             * @description DNI/NIE
             */
            identifier_value: string;
            /** Name Given */
            name_given: string;
            /** Name Family */
            name_family: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Gender */
            gender?: string | null;
            /** Telecom Phone */
            telecom_phone?: string | null;
            /** Telecom Email */
            telecom_email?: string | null;
            /** Id */
            id: string;
            /** Age */
            age: number;
            /**
             * Allergies
             * @default []
             */
            allergies: components["schemas"]["AllergyResponse"][];
            /**
             * Meta Created At
             * Format: date-time
             */
            meta_created_at: string;
            /**
             * Meta Updated At
             * Format: date-time
             */
            meta_updated_at: string;
        };
        /**
         * PatientSummary
         * @description Schema for patient in search results.
         */
        PatientSummary: {
            /** Id */
            id: string;
            /** Identifier Value */
            identifier_value: string;
            /** Name Given */
            name_given: string;
            /** Name Family */
            name_family: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Age */
            age: number;
            /** Gender */
            gender: string | null;
            /** Telecom Phone */
            telecom_phone: string | null;
            /** Has Allergies */
            has_allergies: boolean;
            /** Allergy Count */
            allergy_count: number;
            /** Encounter Count */
            encounter_count: number;
            /** Last Encounter At */
            last_encounter_at: string | null;
        };
        /**
         * PatientUpdate
         * @description Schema for updating a patient (partial).
         */
        PatientUpdate: {
            /** Name Given */
            name_given?: string | null;
            /** Name Family */
            name_family?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Gender */
            gender?: string | null;
            /** Telecom Phone */
            telecom_phone?: string | null;
            /** Telecom Email */
            telecom_email?: string | null;
        };
        /**
         * PractitionerResponse
         * @description Practitioner response schema.
         */
        PractitionerResponse: {
            /** Id */
            id: string;
            /** Identifier Value */
            identifier_value: string;
            /** Name Given */
            name_given: string;
            /** Name Family */
            name_family: string;
            /** Qualification Code */
            qualification_code: string | null;
            /** Telecom Email */
            telecom_email: string | null;
        };
        /** TemplateCreate */
        TemplateCreate: {
            /** Name */
            name: string;
            /** Diagnosis Text */
            diagnosis_text: string;
            /** Diagnosis Code */
            diagnosis_code?: string | null;
            /** Medications */
            medications: components["schemas"]["MedicationItem"][];
            /** Instructions */
            instructions?: string | null;
            /**
             * Is Favorite
             * @default false
             */
            is_favorite: boolean;
        };
        /** TemplateListResponse */
        TemplateListResponse: {
            /** Items */
            items: components["schemas"]["TemplateResponse"][];
            /** Total */
            total: number;
        };
        /** TemplateResponse */
        TemplateResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Diagnosis Text */
            diagnosis_text: string;
            /** Diagnosis Code */
            diagnosis_code?: string | null;
            /** Medications */
            medications: components["schemas"]["MedicationItem"][];
            /** Instructions */
            instructions?: string | null;
            /** Is Favorite */
            is_favorite: boolean;
            /**
             * Is Global
             * @default false
             */
            is_global: boolean;
        };
        /** TemplateUpdate */
        TemplateUpdate: {
            /** Name */
            name?: string | null;
            /** Diagnosis Text */
            diagnosis_text?: string | null;
            /** Diagnosis Code */
            diagnosis_code?: string | null;
            /** Medications */
            medications?: components["schemas"]["MedicationItem"][] | null;
            /** Instructions */
            instructions?: string | null;
            /** Is Favorite */
            is_favorite?: boolean | null;
        };
        /**
         * TokenResponse
         * @description Token response schema.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            practitioner: components["schemas"]["PractitionerResponse"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PractitionerResponse"];
                };
            };
        };
    };
    list_patients_api_v1_patients__get: {
        parameters: {
            query?: {
                /** @description Search by name or DNI */
                search?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_v1_patients__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_api_v1_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_api_v1_patients__patient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_allergies_api_v1_patients__patient_id__allergies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllergyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_allergy_api_v1_patients__patient_id__allergies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllergyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllergyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_allergy_api_v1_patients__patient_id__allergies__allergy_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
                allergy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patient_encounters_api_v1_encounters_patient__patient_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_encounter_api_v1_encounters_patient__patient_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_encounter_api_v1_encounters__encounter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_encounter_api_v1_encounters__encounter_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EncounterUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EncounterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates__get: {
        parameters: {
            query?: {
                /** @description Search by name or diagnosis */
                search?: string | null;
                /** @description Filter favorites only */
                favorites_only?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_template_api_v1_templates_match_get: {
        parameters: {
            query: {
                /** @description Diagnosis text to match */
                diagnosis: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prescription_preview_api_v1_prescriptions__encounter_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_prescription_pdf_api_v1_prescriptions__encounter_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                encounter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
